metadata:
  favicon: ''
  title: New module
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
  vibeAppPhase: impl
  vibeAppConnectedDatasources:
    - Rzain website_c07KQzEEij
  vibeAppAutoApplyMigrations: true
  chatId: '68714'
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
  hideRenderCachingSettings: false
internalType: vibe_project
id: yxfU2MWIaL
